version: "3.9"

services:
  postgres-account:
    image: postgres:15
    container_name: postgres-account
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_account_data:/var/lib/postgresql/data

volumes:
  postgres_account_data: